name: mymoney
description: "A simple Flutter project for managing personal finances."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.2
  cupertino_icons: ^1.0.6
  calendar_appbar: ^0.0.6
  intl: ^0.17.0
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.2.0+1
  build_runner: ^2.2.1
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/money.gif
  uses-material-design: true
